"""login_remindme

Revision ID: 1f2bb1b4804e
Revises: c666a50993e5
Create Date: 2025-10-04 15:10:48.531510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2bb1b4804e'
down_revision = 'c666a50993e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created', hackspace_storage.database.UTCDateTime(), nullable=False),
    sa.Column('expiry', hackspace_storage.database.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_external_id'), ['external_id'], unique=True)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('remind_me')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remind_me', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('login', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_external_id'))

    op.drop_table('login')
    # ### end Alembic commands ###
